[slot_0]
display_color = #2CDA29
material = ABS
vendor = 
name = 
nozzle_temp = 
bed_temp = 

[slot_1]
display_color = #FF7A00
material = ASA
vendor = 
name = 
nozzle_temp = 
bed_temp = 

[slot_2]
display_color = #EECB07
material = PLA
vendor = 
name = 
nozzle_temp = 
bed_temp = 

[slot_3]
display_color = #AE46FF
material = PETG
vendor = 
name = 
nozzle_temp = 
bed_temp = 

